### ISSUE TITLE
Bugs out when trying a Nav-> Nav Transfer

### ISSUE THREAD

**Issue by matt-auckland** [NAVCoin/NavMorph#136]
Repro:
Do a nav to nav estimate

Not related to the Nav transfer per say but, seems to be related to a race condition from getting the minTransactionAmount. 
Needs some more investigation.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-22T01:10:06+13:00","ped":"2017-11-22T03:43:17+13:00"})

**Comment by ro-savage** [comment]
Not enough information.
