### ISSUE TITLE
Pre flight controller

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/NavMorph#156]
After the process handler initialises we want to run some pre-flight checks before we start processing.

* [ ] validate any settings parsed into the pre flight controller.
* [x] run getinfo to check the daemon is responsive and get the daemons reported block height.
* [x] run getblockcount to get the network block height
* [x] create getblockcount RPC client method
* [x] create getWalletInfo RPC client method
* [x] make sure the daemon is within x blocks of the network 
* [x] check the wallet is unlocked
* [x] return success or failure to the process handler and any data required.
* [x] data parsed back: balance
* [ ] unit test coverage.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"ped":"2017-11-06T21:00:00+13:00"})

**Comment by navtrello** [comment]
➤ Matt commented:

I propose we remove the validation from this ticket as we don't have to validate anything (everything comes from a config which is checked when we start the server)
