### ISSUE TITLE
Investigate the best way to batch send navtech transactions.

### ISSUE THREAD

**Issue by navtrello** [NAVCoin/NavMorph#161]
* Use the anonsend feature of the RPC wallet
* Create the transactions in JS and use the RawTx send
* Do we split the transactions or not? Can we specify inputs and split the transactions?
* Do we do the querying, encyrption and tx creation in Javascript or not.
* Size building this function into the RPC wallet
* Only use 1 navtech server per transaction cycle

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by ro-savage** [comment]
Why would be batch transactions? Seems like something we should only worry about once we have enough transaction going through to actually batch.

I think this should be closed, and remade if/when we decide batch transaction.

**Comment by ro-savage** [comment]
@craigmacgregor @matt-auckland

**Comment by aguycalled** [comment]
navtech transactions can not be batched, it's only possible to have one anon destination per tx
