### ISSUE TITLE
Investigate JS naming conventions and convert vars/files to new convention.

### ISSUE THREAD

**Issue by navtrello** [NAVCoin/NavMorph#179]
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-02-23T18:00:00+13:00","ped":"2018-02-24T07:20:00+13:00"})

**Comment by ro-savage** [comment]
Closed by PR #200
