### ISSUE TITLE
Investigate use of sockets.

### ISSUE THREAD

**Issue by navtrello** [NAVCoin/NavMorph#180]
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-02-24T07:20:00+13:00","ped":"2018-02-24T20:40:00+13:00"})

**Comment by ro-savage** [comment]
We are going to keep these for now.
