### ISSUE TITLE
Set up Prettier and confirm ESLint config

### ISSUE THREAD

**Issue by navtrello** [NAVCoin/NavMorph#186]
Standardise this and share across JS projects

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-02-28T01:00:00+13:00","ped":"2018-03-01T17:00:00+13:00"})

**Comment by ro-savage** [comment]
Closed by PR #200
