### ISSUE TITLE
Add logging (Front End)

### ISSUE THREAD

**Issue by matt-auckland** [NAVCoin/NavMorph#75]
Front end logging to capture browser errors.

Investigate options for logging browser errors to our server or a service.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by matt-auckland** [comment]
Should this be split into an investigation story and an implementation story?

**Comment by craigmacgregor** [comment]
Try Rollbar, it has a free tier and ive heard of devs i know using it before.

https://rollbar.com/

**Comment by navtrello** [comment]
➤ Rowan Savage commented:

Suggest we use https://sentry.io/pricing/
Reasons:

  * More popular (twice as popular on StackShare)
  * Cheaper
  * Angular 2 integration
  * 10k vs 5k errors on the free plan
  * seems to have same feature set

**Comment by navtrello** [comment]
➤ Rowan Savage commented:

Usually error logging on frontend would be a production only thing, and during dev you want errors thrown to the console, and your app to crash on major errors.

Is that the plan with this error logging? Or is it going to be used in Development as well? @craigmacgregor2

**Comment by mdelucchi** [comment]
Have used Sentry on past projects. Great choice.

**Comment by navtrello** [comment]
➤ Rowan Savage commented:

We are going to move this to the backlog until other work has taken place.
We need to better define our error handling and what is important to log.
And then this only need to be setup for production, so until we are ready-ing a production release this can remain in the back log.
